config/routes.rb
Decade::Application.routes.draw do
  
  scope "/knox" do
    resource :gate, :controller => 'user_sessions', :path_names => { :new => 'open' } do
      get 'logout', :action => 'destroy'
    end
    resources :images
  end
  
  
  
  get ':y/:m/:d/photo.small', :controller => 'public', :action => "small_photo", :y => /\d{4}/, :m => /\d{1,2}/, :d => /\d{1,2}/
  get ':y/:m/:d/photo', :controller => 'public', :action => "photo", :y => /\d{4}/, :m => /\d{1,2}/, :d => /\d{1,2}/
  get ':y/:m/:d', :controller => 'public', :action => "view", :y => /\d{4}/, :m => /\d{1,2}/, :d => /\d{1,2}/
  get ':y/:m', :controller => 'public', :action => "month", :y => /\d{4}/, :m => /\d{1,2}/
  get ':y', :controller => 'public', :action => "year", :y => /\d{4}/
  
  get 'archive', :controller => 'public', :action => 'archive'
  get 'about', :controller => 'public', :action => 'about'
  get 'syndicate', :controller => 'public', :action => 'syndicate'
  
  root :to => 'public#index'

end

app/models/image.rb
class Image < ActiveRecord::Base
  
  before_validation :fetch_flickr_details
  
  def self.from_decade(decade_image)
    i = Image.new(decade_image)
    i.full_path_url = i.date.strftime("http://cdn.m.ac.nz/decade/images/%Y%m%d.jpg")
    i.thumbnail_url = i.date.strftime("http://cdn.m.ac.nz/decade/images/small/%Y%m%d.jpg")
    i.save
  end
  
  def fetch_flickr_details
    if photo_id?
      update_flickr_info(photo_id)
    end
  end
  
  def permalink (full = false)
    r = self.date.strftime("/%Y/%m/%d/")
    r = DC_CONFIG[:BASE].gsub(/\/$/, "") + r if full
    r
  end


  def prev
    self.class.where('date < ?', self.date).order('date DESC').first
  end
  def next
    self.class.where('date > ?', self.date).order('date ASC').first
  end
  
  private
  
  class FlickrAPI
    include HTTParty
    base_uri 'www.flickr.com'
    format :json
    
    def self.photoInfo(photo_id, options = {})
      options.merge! :photo_id => photo_id, :method => 'flickr.photos.getInfo', :format => 'json', :api_key => ENV['FLICKR_KEY'], :nojsoncallback => 1
      res = get '/services/rest/', :query => options
      res['stat'] == "ok" && res['photo']
    end
    
  end
  
  def gen_flickr_url(photo, size)
    "http://farm#{ photo['farm'] }.static.flickr.com/#{ photo['server']}/#{ photo['id'] }_#{ photo['secret'] }#{ size && ("_" + size) }.jpg"
  end
  
  def update_flickr_info(photo_id)
    f = FlickrAPI.photoInfo(photo_id)
    self.flickr_url = f['urls']['url'][0]['_content']
    self.full_path_url = gen_flickr_url(f, 'b')
    self.thumbnail_url = gen_flickr_url(f, 's')
    
    self.caption = f['title']['_content'] if self.caption.blank?
    self.description = f['description'] if self.caption.blank?
    
    logger.info "FFS" + self.to_yaml
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  
  login_field :login
  
  def to_key
    new_record? ? nil : [ self.send(self.class.primary_key) ]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :current_user_session, :current_user
 
  private
    def current_user_session
      logger.debug "ApplicationController::current_user_session"
      return @current_user_session if defined?(@current_user_session)
      @current_user_session = UserSession.find
    end
 
    def current_user
      logger.debug "ApplicationController::current_user"
      return @current_user if defined?(@current_user)
      @current_user = current_user_session && current_user_session.user
    end
 
    def require_user
      logger.debug "ApplicationController::require_user"
      unless current_user
        store_location
        flash[:notice] = "You must be logged in to access this page"
        redirect_to new_gate_path
        return false
      end
    end
 
    def require_no_user
      logger.debug "ApplicationController::require_no_user"
      if current_user
        store_location
        flash[:notice] = "You must be logged out to access this page"
        redirect_to root_path
        return false
      end
    end
 
    def store_location
      session[:return_to] = request.request_uri
    end
 
    def redirect_back_or_default(default)
      redirect_to(session[:return_to] || default)
      session[:return_to] = nil
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  
  before_filter :require_user
  
  # layout 'admin'
  
  def index
    redirect_to root_path    
  end
  
  def new
    @pgtitle = "New image"
    @image = Image.new
    @image.date = Time.now
  end
  
  def create
    @image = Image.new params[:image]
    if @image.save
      redirect_to @image.permalink
    else
      render :action => :new
    end
  end
  
  def show
    redirect_to edit_image_path(params[:id])
  end
  
  def edit
    @pgtitle = "Edit image"
    @img = @image = Image.find(params[:id])
  end
  
  def update
    @image = Image.find(params[:id])
    if @image.update_attributes(params[:image])
      redirect_to @image.permalink
    else
      render :action => :edit
    end
  end
  
  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    redirect_to images_path
  end
  
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  
  respond_to :html
  respond_to :atom, :rss, :only => :syndicate
  
  def index
    images = Image.order('date DESC').limit(7).all
    @img = images.first
    @links = images.reverse
  end
  
  def view
    date = params[:y] + "-" + params[:m] + "-" + params[:d]
    @img = Image.where(:date => date).first
    if @img.nil?
      redirect_to '/'
      return false
    end
    @show_prevNext = true
    @pgtitle = @img.caption + " - " + @img.date.strftime("%B %d, %Y")
  end
  
  def photo  
    date = params[:y] + "-" + params[:m] + "-" + params[:d]
    @img = Image.where(:date => date).first
    if @img.nil?
      redirect_to '/'
      return false
    end
    redirect_to @img.full_path_url
  end
  
  def small_photo  
    date = params[:y] + "-" + params[:m] + "-" + params[:d]
    @img = Image.where(:date => date).first
    if @img.nil?
      redirect_to '/'
      return false
    end
    redirect_to @img.thumbnail_url
  end
  
  def about
    @pgtitle = "About"
  end
  
  def syndicate
    @pgtitle = "Syndication"
    respond_with(@images = Image.order('date DESC').limit(10))
  end
  
  def archive
    @start_year = Image.first.date.year
    @end_year = Image.last.date.year
    @pgtitle = "Archive"
  end
  
  def month
    redirect_to "/#{ params[:y] }#month-#{ params[:m] && params[:m].to_i }"
  end
  
  def year
    year = params[:y]
    if Rails.env.production?
      @imgs = Image.where('date > ? and date < ?', "#{year.to_i - 1}-12-31", "#{year.to_i + 1}-01-01").order('date ASC').all
    else
      @imgs = Image.where('date like ?', "#{year}-%").order('date ASC').all
    end
    raise ActiveRecord::RecordNotFound if @imgs.empty?
    @pgtitle = @imgs.first.date.strftime("%Y") + " Archives"
  end   
  
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => :destroy
 
  def new
    @user_session = UserSession.new
  end
 
  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      flash[:notice] = "Login successful!"
      redirect_back_or_default images_url
    else
      render :action => :new
    end
  end
 
  def destroy
    current_user_session.destroy
    flash[:notice] = "Logout successful!"
    redirect_back_or_default new_gate_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/images/_form.html.erb
<%= error_messages_for 'image' %>

<table class="form" cellpadding="0" cellspacing="0">
  
  <% if @image.new_record? -%>
  <tr><td class="labels"><label for="decade_date">Date</label></td><td class="fields">
    <%= f.date_select :date %>
  </td></tr>
  <% else %>
  <tr><td class="labels"><label for="decade_date">Date</label></td><td class="fields">
    <%= @image.date %>
  </td></tr>
  <% end -%>

  <tr><td class="labels"><label for="decade_description">Flickr ID</label></td><td>
    <%= f.text_field :photo_id, :size => 58, :class => 'normal_i_width' -%></td></tr>

  <tr><td class="labels"><label for="decade_caption">Title</label></td><td class="fields">
    <%= f.text_field :caption, :size => 58, :class => 'normal_i_width' -%></td></tr>

  <tr><td><label for="decade_description">Description</label></td><td>
    <%= f.text_area :description, :rows => '4', :wrap => 'virtual', :class => 'normal_i_width' %><br/>



  <tr><td class="labels"><label for="decade_description">Full Image</label></td><td>
    <%= f.text_field :full_path_url, :size => 58, :class => 'normal_i_width' -%></td></tr>
  
  <tr><td class="labels"><label for="decade_description">Thumbnail</label></td><td>
    <%= f.text_field :thumbnail_url, :size => 58, :class => 'normal_i_width' -%></td></tr>
  
  <tr><td class="labels"><label for="decade_description">Flickr URL</label></td><td>
    <%= f.text_field :flickr_url, :size => 58, :class => 'normal_i_width' -%></td></tr>

</table>

app/views/images/edit.html.erb
<div class="page">
  <div id="header">
  	<p>Required fields in <b>bold</b>.</p>
  	<% if flash[:notice] %><div class="green flash"><b>Success:</b> <%= flash[:notice] %></div><% end -%>
  </div>

  <table class="super aboutframe" cellspacing="0" cellpadding="0">
  	<tr>
  		<td valign="top" class="no_pad" style="width: 580px;">

        <% form_for @image do |f| %>
  			  <%= render :partial => 'form', :locals => { :f => f } %>
  			  <%= submit_tag 'Update this Photo', :class => 'submit' %>
  			<% end %>

  		</td>

  	</tr>
  </table>
</div>

app/views/images/new.html.erb
<div class="page">
  <div id="header">
  	<p>Required fields in <b>bold</b>.</p>
  	<% if flash[:notice] %><div class="green flash"><b>Success:</b> <%= flash[:notice] %></div><% end -%>
  </div>
  
  <table class="super aboutframe" cellspacing="0" cellpadding="0">
  	<tr>
  		<td valign="top" class="no_pad" style="width: 580px;">

        <% form_for @image do |f| %>
  			  <%= render :partial => 'form', :locals => { :f => f } %>
  			  <%= submit_tag 'Create this Photo', :class => 'submit' %>
  			<% end %>

  		</td>

  	</tr>
  </table>
  <br/>
</div>

app/views/layouts/admin.html.erb
<html>
<head>
	<title><%= 'Decade' %></title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8"/>
	<%= stylesheet_link_tag '/stylesheets/admin.css' %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body<% if @onload %> onload="doFieldSelect(<%= @onload %>);"<% end %>>
    
<% if @update_checker -%>
<div id="message">
    <%= @update_checker %>
</div>
<% end -%>


<div id="admin_nav">
	<ul class="navlist">
		<li><a accesskey="1" href="/images" title="Images">Images</a></li>
		<li class="end"><a accesskey="1" href="/images/new" title="New Image">New Image</a></li>
	</ul>
	<ul class="navlist right">
		<li><a accesskey="l" href="/knox/gate/logout" title="Logout">Logout</a></li>
		<li class="end"><a accesskey="v" href="/" target="_blank" title="View Site">View Site</a></li>
	</ul><br/>
</div>
	
<div id="box">
	<%= yield %>
</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<!--
	Copyright (C) 2002-2011 Patrick Quinn-Graham, All Rights Reserved.
	Please feel free to learn from this code, but please don't steal the design.
-->

<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><%= (@pgtitle + " - ") unless @pgtitle.nil? %>Project Decade</title>
    <link rel="alternate" type="application/atom+xml" title="Atom" href="/syndicate.atom" />
    
		<script type="text/javascript" src="http://use.typekit.com/urd7xcf.js"></script>
    <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
    
	  <style type="text/css">
      @import url( <%= DC_CONFIG[:ASSETSBASE] -%>c/style.css?2011020901 );
    </style>
    <% if current_user %><%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <% end -%>
  </head>
  <body>
    <div class="logodiv">
      <h1>project <strong>decade</strong></h1>
      <div class="tagline">one geek's life in photographs</div>
    </div>
    
    
    <div class="logozone">
      <div class="details">
      <% if @img.nil? %>
        <h2><%= @pgtitle %></h2>
      <% else %>
        <h2><%= @img.caption %></h2>
        <p>
          <%= @img.description %>
        </p>
        <p class="date"><%= @img.date.strftime('%d %B, %Y') %></p>
      <% end %>
      </div>
      <div class="navigator">
        <ul class="menu2">
        <% if (!@links.nil?)
        	for link in @links -%>
    	   <li><a href="<%= link.permalink %>"><%= link.date.strftime("%A") %></a></li>
        <% end 
       end %>
        <% if @show_prevNext %>
        <% unless @img.prev.nil? %>
        	<li>&laquo; <%= link_to "Previous", @img.prev.permalink %></li>
        <% end %>
        <% unless @img.next.nil? %>
        	<li><%= link_to "Next", @img.next.permalink %> &raquo;</li>
        <% end %>
        <% end %>
        </ul>
      </div>
      <div class="menuHolder">
      <ul class="menu">
        <li><a href="/">Home</a></li>
        <li><a href="/about">About</a></li>
        <li><a href="/archive">Archive</a></li>
        <li><a href="/syndicate">Subscribe/Syndicate</a></li>
        <% if current_user %>
          <li>&nbsp;</li>
          <li><%= link_to 'New image', new_image_path %></li>
          <% if @img %>
            <li><%= link_to 'Edit image', @img %></li>
            <li><%= link_to 'Delete image', @img, :method => :delete %></li>
          <% end %>        
          <li><%= link_to 'Logout', logout_gate_path %></li>
        <% end %>
      </ul>
      <br style="clear: both;" />
    </div>
  </div>
  <div class="copyright">
  	<p>
      Copyright &copy; 2004-2011
      <a href="http://thepatrick.com.au/">Patrick Quinn-Graham</a>. 
      <a href="http://creativecommons.org/licenses/by/3.0/">Some rights reserved</a>. <%= link_to('Login', new_gate_path) + "." unless current_user %>
   </p>
  </div>

    <%= yield %>

    <div class="printcopy">
      <hr />
      <p>Printed from The Decade Project (www.decade.geek.nz). <br/>
       The contents are licensed under the Creative Commons
       Attribution 3.0 license.<br/>
       See http://creativecommons.org/licenses/by/3.0/
       for details.</p>
      <hr />
    </div>
    <script src="http://www.google-analytics.com/urchin.js" type="text/javascript"></script>
    <script type="text/javascript">
      _uacct = "UA-340421-3";
      urchinTracker();
    </script>
  </body>
</html>

app/views/user_sessions/new.html.erb
<div class="photoframe">
<h1>Login</h1>
 
<%= form_for @user_session, :url => {:action => "create"} do |f| -%>
  <%= f.error_messages %>
  <div>
    <input id="user_session_login" name="user_session[login]" size="30" type="text" placeholder="Login" value="<%= @user_session.login -%>">
  </div>
  <div>
    <input id="user_session_password" name="user_session[password]" size="30" type="password" placeholder="Password">
  </div>
  <div>
    <%= f.check_box :remember_me %>
    <%= f.label :remember_me %>
  </div>
  <div>
    <%= f.submit "Login" %>
  </div>
<% end -%>  
</div>